version: '3.8'

services:
  app:
    build: .
    ports:
      - "4001:4001"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    restart: always

  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./database.db:/database.db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
